[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://cannabis-tracker-app-production.up.railway.app/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
